<?php

namespace lcssoft\report\widgets\blockselectionwidget;

use yii\base\Widget;

class BlockSelectionWidget extends Widget
{
    public $availableData = [];

    public $assignedData = [];

    public $urlAssign;

    public $urlRemove;

    public $urlRefresh;

    /** @desc
     *  '<jquery_event>' [
     *    'elementId' => '<element_id>',
     *    'submitArg' => '<arg_name>',
     *   ]
     */
    public $filterElementAffected = [];
    /** @desc
     *   [
     *    'key' => 'value',
     *   ]
     *  - Html button submit: <a data-<key>="<value>" >submit</a>
     *  - JS script submit: $.post(..,{"<key>":"<value>"})
     */
    public $submitData = [];


    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('view');
    }
}