version: '3.2'

services:

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: '${SERVICE_REPO}:${SERVICE_VERSION}-local'
    env_file:
      - .env
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
#      - ./frontend/apache2:/etc/apache2/sites-available:delegated
    networks:
      - lcs-internal-service-network

  backend:
    image: '${SERVICE_REPO}:${SERVICE_VERSION}-local'
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./backend/apache2/conf.d:/etc/apache2/sites-available:delegated
    networks:
      - lcs-internal-service-network

networks:
  lcs-internal-service-network:
    external: true

#  mysql:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=verysecret
#      - MYSQL_DATABASE=yii2advanced
#      - MYSQL_USER=yii2advanced
#      - MYSQL_PASSWORD=secret

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret